erm/app/project/__init__.py
from flask import Blueprint

project_bp = Blueprint('project', __name__)

from . import views

erm/app/project/views.py
import os
import arrow
import requests
import wtforms
import pypandoc
from flask import render_template, request, redirect, url_for, flash, Response, send_file
from flask_login import login_required, current_user
from sqlalchemy_continuum import version_class
from werkzeug.utils import secure_filename
from . import project_bp as project
from .forms import *
from app.main.models import User, MailInfo
from app import mail
from pydrive.auth import ServiceAccountCredentials, GoogleAuth
from pydrive.drive import GoogleDrive
from flask_mail import Message

STIN_EMAIL = os.environ.get('MAIL_USERNAME')


def send_mail(recp, title, message):
    mail_info = MailInfo.query.first()
    signature = '\n\n-----------------------\n' + mail_info.signature
    message = Message(subject=title, body=message + signature, recipients=[recp])
    mail.send(message)


gauth = GoogleAuth()
keyfile_dict = requests.get(os.environ.get('GOOGLE_APPLICATION_CREDENTIALS')).json()
scopes = ['https://www.googleapis.com/auth/drive']
gauth.credentials = ServiceAccountCredentials.from_json_keyfile_dict(keyfile_dict, scopes)
drive = GoogleDrive(gauth)

ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}
GANTT_ACTIVITIES = dict([(1, 'พัฒนาโครงร่างการวิจัยและเครื่องมือการวิจัย'),
                         (2, 'เสนอโครงร่างการวิจัยเพื่อขอรับการพิจารณาจริยธรรมฯ'),
                         (3, 'เสนอขอรับทุนอุดหนุนการวิจัย'),
                         (4, 'ผู้ทรงคุณวุฒิตรวจสอบและแก้ไข'),
                         (5, 'ติดต่อประสานงานเพื่อขอเก็บข้อมูล'),
                         (6, 'ดำเนินการเก็บรวบรวมข้อมูล'),
                         (7, 'วิเคราะห์ผลการวิจัยและอภิปรายผล'),
                         (8, 'จัดทำรายงานการวิจัยและเตรียมต้นฉบับตีพิมพ์งานวิจัย')]
                        )


def make_project_archive(project):
    """Create an archive of a project.
    :param project: a project model
    :return: archive model
    """

    archive = ProjectRecordArchive(
        project_record_id=project.id,
        archived_at=arrow.now(tz='Asia/Bangkok').datetime,
        title_th=project.title_th,
        subtitle_th=project.subtitle_th,
        title_en=project.title_en,
        subtitle_en=project.subtitle_en,
        objective=project.objective,
        method=project.method,
        intro=project.intro,
        status=project.status,
        prospected_journals=project.prospected_journals,
        use_applications=project.use_applications,
        created_at=project.created_at,
        updated_at=project.updated_at,
        creator_id=project.creator_id
    )
    members = []
    for member in project.members:
        if member.user:
            mem = {
                'role': member.role,
                'fullname_th': member.user.profile.fullname_th,
                'fullname_en': member.user.profile.fullname_en,
                'title_th': member.user.profile.title_th,
                'title_en': member.user.profile.title_en,
            }
        else:
            mem = {
                'role': member.role,
                'fullname_th': member.lastname,
                'fullname_en': member.firstname,
                'title_th': member.title,
                'title_en': '',
            }
        members.append(mem)
    figures = []
    for figure in project.figures:
        fig = {
            'title': figure.title,
            'desc': figure.desc,
            'fignum': figure.fignum,
            'url': figure.url,
        }
        figures.append(fig)
    milestones = []
    for milestone in project.milestones:
        mst = {
            'status': milestone.status,
            'detail': milestone.detail
        }
        milestones.append(mst)
    archive.members = members
    archive.figures = figures
    archive.milestones = milestones
    return archive


@project.route('/')
def list_projects():
    projects = ProjectRecord.query.filter_by(status='finished')
    return render_template('project/index.html', projects=projects)


@project.route('/user/<int:user_id>')
@login_required
def list_created_projects(user_id):
    user = User.query.get(user_id)
    projects = user.projects
    return render_template('project/created_projects.html', projects=projects)


@project.route('/detail/<int:project_id>')
@login_required
def display_project(project_id):
    project = ProjectRecord.query.get(project_id)

    if project.creator_id != current_user.id:
        return redirect(url_for('project.display_shorten', project_id=project.id))

    gantt_activities = []
    for a in sorted(project.gantt_activities, key=lambda x: x.task_id):
        gantt_activities.append([
            str(a.task_id),
            GANTT_ACTIVITIES.get(a.task_id),
            a.start_date.isoformat(),
            a.end_date.isoformat(),
            None, 0, None,
            a.start_date,
            a.end_date,
            a.id
        ])
    return render_template('project/detail.html', project=project, gantt_activities=gantt_activities)


@project.route('/detail/<int:project_id>/shorten')
@login_required
def display_project_shorten(project_id):
    project = ProjectRecord.query.get(project_id)
    return render_template('project/detail_shorten.html', project=project)


@project.route('/edit/<int:project_id>', methods=['GET', 'POST'])
@login_required
def edit_project(project_id):
    project = ProjectRecord.query.get(project_id)

    def edit_project_form_factory(project):
        class EditProjectRecordForm(ProjectRecordForm):
            parent = QuerySelectField(
                query_factory=lambda: ParentProjectRecord.query.all(),
                widget=wtforms.widgets.Select(),
                allow_blank=True,
                blank_text='โครงการเดี่ยว',
                default=project.parent_project
            )

        return EditProjectRecordForm

    EditProjectRecordForm = edit_project_form_factory(project)
    form = EditProjectRecordForm(obj=project)
    title = 'Edit Project Record'
    if request.method == 'POST':
        if form.validate_on_submit():
            form.populate_obj(project)
            project.updated_at = arrow.now(tz='Asia/Bangkok').datetime
            project.parent_project = form.parent.data

            if form.contract_upload.data:
                upfile = form.contract_upload.data
                filename = secure_filename(upfile.filename)
                upfile.save(filename)
                file_drive = drive.CreateFile({'title': filename})
                file_drive.SetContentFile(filename)
                file_drive.Upload()
                permission = file_drive.InsertPermission({'type': 'anyone',
                                                          'value': 'anyone',
                                                          'role': 'reader'})
                project.contract_url = file_drive['id']

            if form.final_report_upload.data:
                upfile = form.final_report_upload.data
                filename = secure_filename(upfile.filename)
                upfile.save(filename)
                file_drive = drive.CreateFile({'title': filename})
                file_drive.SetContentFile(filename)
                file_drive.Upload()
                permission = file_drive.InsertPermission({'type': 'anyone',
                                                          'value': 'anyone',
                                                          'role': 'reader'})
                project.final_report_url = file_drive['id']
            db.session.add(project)
            db.session.commit()
            flash('Data have been updated.', 'success')
        else:
            flash('Error occurred.', 'danger')
        return redirect(url_for('project.display_project', project_id=project.id))
    return render_template('project/project_edit.html', form=form, title=title, project=project)


@project.route('/parents/add', methods=['GET', 'POST'])
@login_required
def add_parent_project():
    form = ParentProjectRecordForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            new_record = ParentProjectRecord()
            form.populate_obj(new_record)
            new_record.created_at = arrow.now(tz='Asia/Bangkok').datetime
            new_record.created_by = current_user
            db.session.add(new_record)
            db.session.commit()
            flash('A new parent project has been created.', 'success')
            return redirect(url_for('project.list_parent_projects'))
    return render_template('project/project_parent_add.html', form=form)


@project.route('/parents/<int:project_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_parent_project(project_id):
    record = ParentProjectRecord.query.get(project_id)
    form = ParentProjectRecordForm(obj=record)
    if request.method == 'POST':
        if form.validate_on_submit():
            form.populate_obj(record)
            db.session.add(record)
            db.session.commit()
            flash('A new parent project has been edited.', 'success')
            return redirect(url_for('project.list_parent_projects'))
        else:
            flash(form.errors, 'danger')
    return render_template('project/project_parent_add.html', form=form)


@project.route('/parents')
@login_required
def list_parent_projects():
    return render_template('project/parent_projects.html')


@project.route('/parents/<int:parent_id>/children')
@login_required
def list_children_projects(parent_id):
    parent = ParentProjectRecord.query.get(parent_id)
    return render_template('project/child_projects.html', parent=parent)


@project.route('/add', methods=['GET', 'POST'])
@login_required
def add_project():
    form = ProjectRecordForm()
    title = 'New Project Record'
    if request.method == 'POST':
        if form.validate_on_submit():
            new_proj = ProjectRecord()
            form.populate_obj(new_proj)
            new_proj.creator = current_user
            current_datetime = arrow.now(tz='Asia/Bangkok').datetime

erm/app/templates/project/budget_item_add.html
{% extends "base.html" %}

{% block title %}Add Budget Item Page{% endblock %}

{% block page_content %}
{% include "nav.html" %}
<section class="section">
    <div class="columns">
        <div class="column is-four-fifths is-offset-1">
            <nav class="breadcrumb has-bullet-separator" aria-label="breadcrumbs">
                <ul>
                    <li><a href="{{ url_for('project.list_created_projects', user_id=current_user.id) }}">Your projects</a></li>
                    <li><a href="{{ url_for('project.display_project', project_id=project_id) }}">Project detail</a></li>
                    <li><a href="{{ url_for('project.list_budget_items', project_id=project_id, milestone_id=milestone_id) }}">Budgets</a></li>
                    <li class="is-active"><a aria-current="page">Add / Edit budget</a></li>
                </ul>
            </nav>
        </div>
    </div>
    <div class="container">
        <div class="columns">
            <div class="column is-one-third is-offset-4">
                <h1 class="title has-text-centered">เพิ่มรายการใช้จ่าย</h1>
                <form class="box" method="post" enctype=multipart/form-data>
                    {{ form.csrf_token }}
                    <div class="field">
                        <label class="label">หมวดค่าใช้จ่าย</label>
                        <div class="select">
                            {{ form.category() }}
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">{{ form.wage.label }}</label>
                        <div class="control">
                            {{ form.wage(class="input") }}
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">{{ form.amount_spent.label }}</label>
                        <div class="control">
                            {{ form.amount_spent(class="input") }}
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">{{ form.detail.label }}</label>
                        <div class="control">
                            {{ form.detail(class="textarea") }}
                        </div>
                    </div>
                    {% if item and item.file_name %}
                    <div class="field">
                        <label class="label">ไฟล์เอกสารแนบ</label>
                        {{ item.file_name }}
                    </div>
                    {% endif %}
                    <div class="field">
                        <label class="label">{{ form.file_upload.label }}</label>
                        <div class="control">
                            {{ form.file_upload() }}
                        </div>
                        {% if item and item.file_name %}
                        <p class="help is-info">ไฟล์ใหม่จะแทนที่ไฟล์เดิม</p>
                        {% endif %}
                    </div>
                    <div class="field">
                        <label class="label">{{ form.file_detail.label }}</label>
                        <div class="control">
                            {{ form.file_detail(class="textarea") }}
                        </div>
                    </div>
                    <div class="field is-grouped is-grouped-centered">
                        <div class="control">
                            <button type="submit" class="button is-success">Create</button>
                        </div>
                        <div class="control">
                            <a href="{{ url_for('project.list_budget_items', project_id=project_id, milestone_id=milestone_id) }}"
                                class="button is-light">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

erm/app/templates/project/detail_shorten.html
{% extends "base.html" %}

{% block title %}Project Detail Page{% endblock %}

{% block page_content %}
{% include "nav.html" %}
<section class="section">
    <div class="columns">
        <div class="column is-four-fifths is-offset-1">
            <nav class="breadcrumb has-bullet-separator" aria-label="breadcrumbs">
                <ul>
                    <li><a href="{{ url_for('project.list_created_projects', user_id=current_user.id) }}">Your projects</a></li>
                    <li class="is-active"><a aria-current="page">Project detail</a></li>
                </ul>
            </nav>
        </div>
    </div>
    <div class="columns">
        <div class="column">
            <div class="container has-text-centered">
                <h1 class="title">Project Detail</h1>
                <h2 class="subtitle is-size-4">{{ project.title_th }}</h2>
                <p>
                    {% for member in project.members %}
                    {% if member.user %}
                    {{ member.user.profile.fullname_th }} ({{ member.role }}),
                    {% else %}
                    {{ member.fullname }} ({{ member.role }}),
                    {% endif %}
                    {% endfor %}
                </p>
            </div>
        </div>
    </div>
    <div class="columns">
        <div class="column is-four-fifths is-offset-1">
            <div class="box">
                <table class="table is-fullwidth is-bordered">
                    {% if project.parent_project %}
                    <tr>
                        <td class="title is-size-5" width="20%">ชุดโครงการ</td><td>{{ project.parent_project }}</td>
                    </tr>
                    {% endif %}
                    <tr>
                        <td class="title is-size-5" width="20%">ชื่อรองภาษาไทย</td><td>{{ project.subtitle_th }}</td>
                    </tr>
                    <tr>
                        <td class="title is-size-5" width="20%">ชื่อภาษาอังกฤษ</td><td>{{ project.title_en }}</td>
                    </tr>
                    <tr>
                        <td class="title is-size-5" width="20%">ชื่อรองภาษาอังกฤษ</td><td>{{ project.subtitle_en }}</td>
                    </tr>
                    <tr>
                        <td class="title is-size-5" width="20%">ที่ปรึกษาโครงการ</td><td>{{ project.mentor }}</td>
                    </tr>
                    <tr>
                        <td class="title is-size-5" width="20%">ประเภทของงานวิจัย</td>
                        <td class="content">{{ project.research_type }}</td>
                    </tr>
                    <tr>
                        <td class="title is-size-5" width="20%">สาขาวิชาการและกลุ่มที่ทำวิจัย</td>
                        <td class="content">{{ project.research_cluster }}</td>
                    </tr>
                    <tr>
                        <td class="title is-size-5" width="20%">คำสำคัญของโครงการวิจัย</td>
                        <td class="content">{{ project.keywords|safe }}</td>
                    </tr>
                    <tr>
                        <td class="title is-size-5" width="20%">บทคัดย่อ</td>
                        <td class="content">{{ project.abstract|safe }}</td>
                    </tr>
                    <tr>
                        <td class="title is-size-5" width="20%">หมวดหมู่</td>
                        <td>
                            <div class="field is-grouped is-grouped-multiline">
                                {% for cat in project.subcategories %}
                                <div class="control">
                                    <div class="tags has-addons">
                                        <p class="tag is-light is-medium is-info">{{ cat.category }}</p>
                                        <p class="tag is-light is-medium">{{ cat.parent }}</p>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="title is-size-5">ผลงานวิจัยตีพิมพ์</td>
                        <td>
                            <table class="table is-striped is-narrow">
                                <thead>
                                <th>เรื่อง</th>
                                <th>วารสาร</th>
                                <th>ประเภท</th>
                                </thead>
                                <tbody>
                                {% for p in project.publications %}
                                <tr>
                                    <td>{{ p.title }}</td>
                                    <td>{{ p.journal.name }}</td>
                                    <td>{{ p.category }}</td>
                                </tr>
                                </tbody>
                                {% endfor %}
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td class="title is-size-5">การนำงานวิจัยไปใช้ประโยชน์</td>
                        <td>
                            <table class="table is-striped is-narrow">
                                <thead>
                                <th>องค์กร สถานที่ ชุมชน</th>
                                <th>รายละเอียดการใช้งานวิจัย</th>
                                <th>วันที่และเวลา</th>
                                </thead>
                                <tbody>
                                {% for app in project.applications %}
                                <tr>
                                    <td>{{ app.org }}</td>
                                    <td>{{ app.detail }}</td>
                                    <td>{{ app.date|localdate }}</td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="has-text-centered">
                <a href="{{ url_for('project.list_projects') }}" class="button is-light is-medium">Back</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

erm/app/templates/project/gantt_activity_add.html
{% extends "base.html" %}

{% block title %}Gantt Chart Activity Page{% endblock %}

{% block page_content %}
{% include "nav.html" %}
<section class="section">
    <div class="columns">
        <div class="column is-four-fifths is-offset-1">
            <nav class="breadcrumb has-bullet-separator" aria-label="breadcrumbs">
                <ul>
                    <li><a href="{{ url_for('project.list_created_projects', user_id=current_user.id) }}">Your projects</a></li>
                    <li><a href="{{ url_for('project.display_project', project_id=project_id) }}">Project detail</a></li>
                    <li><a href="{{ url_for('project.list_gantt_activity', project_id=project_id, milestone_id=milestone_id) }}">Gantt chart</a></li>
                    <li class="is-active"><a aria-current="page">Add activity</a></li>
                </ul>
            </nav>
        </div>
    </div>
    <div class="container">
        <div class="columns">
            <div class="column is-one-third is-offset-4">
                <h1 class="title has-text-centered">Add Gantt Chart Activity</h1>
                {% include "messages.html" %}
                <form class="box" method="post" enctype=multipart/form-data>
                    {{ form.csrf_token }}
                    <div class="field">
                        <label class="label">{{ form.task_id.label }}</label>
                        <div class="select">
                            {{ form.task_id() }}
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">{{ form.start_date.label }}</label>
                        <div class="control">
                            {{ form.start_date(class="input", type="text") }}
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">{{ form.end_date.label }}</label>
                        <div class="control">
                            {{ form.end_date(class="input", type="text") }}
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">{{ form.completion.label }}</label>
                        <div class="control">
                            {{ form.completion(class="input") }}
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">{{ form.detail.label }}</label>
                        <div class="control">
                            {{ form.detail(class="textarea") }}
                        </div>
                    </div>
                    <div class="field is-grouped is-grouped-centered">
                        <div class="control">
                            <a href="{{ url_for('project.list_gantt_activity', project_id=project_id, milestone_id=milestone_id) }}"
                               class="button is-light">Back</a>
                        </div>
                        <div class="control">
                            <button type="submit" class="button is-success">Create</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block scripts %}
{{ super() }}
<script>
    $(document).ready(function() {
        $('input[name="start_date"]').daterangepicker({
            singleDatePicker: true,
            showDropdowns: true,
            locale: {
                format: 'YYYY-MM-DD'
            }
        });
        $('input[name="end_date"]').daterangepicker({
            singleDatePicker: true,
            showDropdowns: true,
            locale: {
                format: 'YYYY-MM-DD'
            }
        });
    });
</script>
{% endblock %}

erm/app/templates/project/gantt_remove.html
{% extends "base.html" %}

{% block title %}Gantt Chart Activity Remove Page{% endblock %}

{% block page_content %}
{% include "nav.html" %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-one-third is-offset-4">
                <h1 class="title has-text-centered">Remove Gantt Chart Activity</h1>
                <div class="box">
                    <article class="message is-danger">
                        <div class="message-header">
                            Dangerous Zone
                            <span class="icon">
                                <i class="fas fa-info-circle"></i>
                            </span>
                        </div>
                        <div class="message-body">
                            คุณต้องการลบกิจกรรมนี้หรือไม่
                        </div>
                    </article>
                    <div class="buttons is-centered">
                        <a href="{{ url_for('project.list_gantt_activity', project_id=project_id, milestone_id=milestone_id) }}" class="button is-light">
                            Cancel
                        </a>
                        <a href="{{ url_for('project.remove_gantt_activity', project_id=project_id, milestone_id=milestone_id, record_id=record.id, confirm='yes') }}"
                           class="button is-danger">
                            <span class="icon">
                               <i class="far fa-trash-alt"></i>
                            </span>
                            <span>Remove</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

erm/app/templates/project/overall_budget_form.html
{% extends "base.html" %}

{% block title %}Project: Add Overall Budget{% endblock %}

{% block page_content %}
{% include "nav.html" %}
<section class="section">
    <div class="columns">
        <div class="column is-four-fifths is-offset-1">
            <nav class="breadcrumb has-bullet-separator" aria-label="breadcrumbs">
                <ul>
                    <li><a href="{{ url_for('project.list_created_projects', user_id=current_user.id) }}">Your projects</a></li>
                    <li><a href="{{ url_for('project.display_project', project_id=project.id) }}">This Project</a></li>
                    <li class="is-active"><a aria-current="page">Overall budget</a></li>
                </ul>
            </nav>
        </div>
    </div>
    <div class="columns">
        <div class="column is-one-third is-offset-4">
            <div class="container has-text-centered">
                <h1 class="title">Add Overall Budget</h1>
                {% include "messages.html" %}
                <div class="box has-text-left">
                    <form method="post">
                        {{ form.csrf_token }}
                        <div class="field">
                            <label class="label">หมวดค่าใช้จ่าย</label>
                            <div class="select">
                                {{ form.sub_category() }}
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">{{ form.wage.label }}</label>
                            <div class="control">
                                {{ form.wage(class="input") }}
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">{{ form.item.label }}</label>
                            <div class="control">
                                {{ form.item(class="input") }}
                            </div>
                        </div>
                        <div class="field is-grouped is-grouped-centered">
                            <div class="control">
                                <a href="{{ url_for('project.display_project', project_id=project.id) }}"
                                   class="button is-light">Back</a>
                            </div>
                            <div class="control">
                                <button type="submit" class="button is-success">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

erm/app/templates/project/parent_projects.html
{% extends "base.html" %}

{% block title %}Parent Projects Page{% endblock %}

{% block page_content %}
{% include "nav.html" %}
<section class="section">
    <div class="columns">
        <div class="column has-text-centered is-two-thirds is-offset-2">
            {% include "messages.html" %}
            <h1 class="title">ชุดโครงการวิจัย</h1>
            <a href="{{ url_for('project.add_parent_project') }}" class="button is-outlined is-primary">
                <span class="icon">
                    <i class="fas fa-folder-plus"></i>
                </span>
                <span>สร้างชุดโครงการใหม่</span>
            </a>
            <hr>
            <table class="table">
                <thead>
                <th>ลำดับ</th>
                <th>ชื่อชุดโครงการ</th>
                <th>ชื่อชุดโครงการย่อย</th>
                <th>English Title</th>
                <th>English Subtitle</th>
                <th>สร้างเมื่อ</th>
                <th></th>
                </thead>
                <tbody>
                {% for project in current_user.created_parent_projects|sort(attribute='created_at', reverse=True) %}
                <tr>
                    <td>{{ loop.index }}</td>
                    <td>{{ project.title_th }}</td>
                    <td>{{ project.subtitle_th }}</td>
                    <td>{{ project.title_en }}</td>
                    <td>{{ project.subtitle_en }}</td>
                    <td>{{ project.created_at|localdatetime }}</td>
                    <td class="buttons">
                        <a href="{{ url_for('project.list_children_projects', parent_id=project.id) }}"
                           class="button is-primary is-rounded is-outlined">
                            <span class="icon">
                                <i class="far fa-eye"></i>
                            </span>
                            <span>
                                ดูโครงการที่เกี่ยวข้อง
                            </span>
                        </a>
                        <a class="button is-link is-rounded is-outlined"
                            href="{{ url_for('project.edit_parent_project', project_id=project.id) }}">
                            <span class="icon">
                                <i class="fas fa-pencil-alt"></i>
                            </span>
                            <span>
                                แก้ไข
                            </span>
                        </a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <a class="button is-light" href="{{ url_for('project.list_created_projects', user_id=current_user.id) }}">Back</a>
        </div>
    </div>
</section>
{% endblock %}