web/project_root/research/urls.py
from django.urls import path
from . import views


app_name = 'research'

urlpatterns = [
    path('', views.project_list, name='project_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:project>/',
         views.project_detail, name='project_detail'),
    path('irb-record/<int:irbid>/',
         views.irb_detail, name='irb_detail'),
]

web/project_root/users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('researchers/', views.list_researchers, name='researchers_list'),
    path('researchers/profile/<int:pk>', views.show_profile, name='profile'),
]

web/project_root/web/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls
from wagtail.core import urls as wagtail_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('research/', include('research.urls', namespace='research')),
    path('staff/', include('users.urls', namespace='staff')),
    re_path(r'^cms/', include(wagtailadmin_urls)),
    re_path(r'^documents/', include(wagtaildocs_urls)),
    re_path(r'^pages/', include(wagtail_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/project_root/users/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import ugettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set.')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')

        return self._create_user(email, password, **extra_fields)


class ResearcherManager(models.Manager):
    def get_queryset(self):
        return super(ResearcherManager, self).get_queryset().filter(is_researcher=True)


class CustomUser(AbstractUser):
    # TODO: Add some other fields for users
    username = None
    email = models.EmailField(_('email address'), unique=True)
    job_position = models.CharField(max_length=64, blank=True)
    acad_position = models.CharField(max_length=64, choices=(
        ('ผู้ช่วยศาสตราจารย์', 'ผู้ช่วยศาสตราจารย์'),
        ('รองศาสตราจารย์', 'รองศาสตราจารย์'),
        ('ศาตราจารย์', 'ศาสตราจารย์'),
    ), blank=True)
    department = models.ForeignKey(
                    'Department', on_delete=models.DO_NOTHING, null=True, blank=True)

    expertise = models.CharField(max_length=250, blank=True)
    avatar = models.ImageField(upload_to='images/', blank=True)
    is_researcher = models.BooleanField('Is a researcher?', default=True)

    objects = UserManager()
    researchers = ResearcherManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        if self.first_name and self.last_name:
            return self.fullname
        return self.email

    @property
    def fullname(self):
        return '{} {} {}'.format(self.acad_position, self.first_name, self.last_name)

    def get_absolute_url(self):
        return reverse('staff:profile',
                       args=[self.pk])

class Department(models.Model):
    name = models.CharField(max_length=250, blank=False)
    parent = models.ForeignKey(
                'Department', on_delete=models.CASCADE, null=True, blank=True,
                related_name='units')

    def __str__(self):
        if self.parent:
            return '{1} - {0}'.format(self.name, self.parent)
        else:
            return self.name

web/project_root/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('email', 'password')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'password')

web/project_root/users/views.py
from django.shortcuts import render, get_object_or_404
from .models import CustomUser

def list_researchers(request):
    reseachers = CustomUser.researchers.all()
    return render(request, 'users/researchers.html', {'researchers': reseachers})


def show_profile(request, pk):
    researcher = CustomUser.objects.get(pk=pk)
    publications = researcher.pubs.all()
    return render(request, 'users/profile.html',
                {'researcher': researcher, 'publications': publications})

web/project_root/users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css" />
    <link rel="stylesheet" href="https://cdn.materialdesignicons.com/2.5.94/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">
    <link rel="stylesheet" href="https://unpkg.com/buefy/dist/buefy.min.css">
</head>
<body>
<section class="hero is-primary is-bold">
    <div class="hero-head">
        <nav class="navbar">
            <div class="container">
                <div class="navbar-brand">
                    <span class="navbar-burger burger" data-target="navbarMenuHeroA">
                        <span></span>
                        <span></span>
                        <span></span>
                      </span>
                </div>
                <div id="navbarMenuHeroA" class="navbar-menu">
                    <div class="navbar-end">
                        <a class="navbar-item"
                            href="{% url 'research:project_list' %}">
                            Projects
                        </a>
                        <a class="navbar-item is-active"
                            href="{% url 'staff:researchers_list' %}">
                            Researchers
                        </a>
                    </div>
                </div>
            </div>
        </nav>
    </div>
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                {% block page_header %}
                Research Projects
                {% endblock %}
            </h1>
            <h1 class="subtitle">
                {% block page_subheader %}
                {% endblock %}
            </h1>
        </div>
    </div>
</section>
    {% block content %}
    {% endblock %}
    {% block scripts %}
    <script src="https://unpkg.com/buefy/dist/buefy.min.js"></script>
    <script src="https://unpkg.com/vue"></script>
    {% endblock %}
</body>
</html>

web/project_root/users/templates/users/profile.html
{% extends "users/base.html" %}

{% block title %}Researchers{% endblock %}
{% block page_header %}Profile Detail{% endblock %}

{% block content %}
    <section class="section">
        <div class="box">
            <div class="has-text-centered">
                <figure class="image is-128x128 container">
                    <img class="is-rounded" src="/media/{{ researcher.avatar }}">
                </figure>
                <h1 class="title">{{ researcher.fullname }}</h1>
                <p>ตำแหน่ง {{ researcher.job_position }}</p>
                <p>สังกัด {{ researcher.department }} </p>
                <hr>
            </div>
            <div>
                <h2 class="title has-text-centered">ผลงานวิจัย</h2>
                {% for pub in publications %}
                    <p class="notification">
                        <p><strong>{{ pub.title }}</strong>, {{ pub.pubdate }}, {{ pub.journal }}</p>
                        <p><a href="{{ pub.url }}">Link to the article</a></p>
                    </p>
                {% endfor %}
            </div>
            <div>
                <h2 class="title has-text-centered">โครงการวิจัย</h2>
                {% for project in researcher.created_projects.all %}
                    <p class="notification">
                        <p><strong>{{ project.th_title }}</strong>, {{ project.th_abstract }}</p>
                        <p>เริ่มโครงการเมื่อวันที่ {{ project.startdate }} <a href="{{ project.get_absolute_url }}">รายละเอียด</a></p>
                    </p>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

web/project_root/users/templates/users/researchers.html
{% extends "research/base.html" %}

{% block title %}Researchers{% endblock %}
{% block page_header %}List of all researchers{% endblock %}

{% block content %}
    <section class="section">
        <table class="table">
            <thead>
                <th>ชื่อ</th>
                <th>สังกัด</th>
            </thead>
            <tbody>
            {% for r in researchers %}
            <tr>
                <td><a href="{{ r.get_absolute_url }}">{{ r.fullname }}</a></td>
                <td>{{ r.department }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </section>
{% endblock %}