erm/app/researcher/forms.py
from wtforms import FieldList, FormField

from app import db
from flask_wtf import FlaskForm
from wtforms_alchemy import (model_form_factory, QuerySelectField)
from wtforms.widgets import Select, ListWidget, CheckboxInput
from wtforms.fields import SelectMultipleField
from .models import *


BaseModelForm = model_form_factory(FlaskForm)


class MultiCheckboxField(SelectMultipleField):
    widget = ListWidget(prefix_label=False)
    option_widget = CheckboxInput()


class ModelForm(BaseModelForm):
    @classmethod
    def get_session(self):
        return db.session


class ProgramForm(ModelForm):
    class Meta:
        model = Program


class ProfileForm(ModelForm):
    class Meta:
        model = Profile

    programs = QuerySelectField('Program',
                                query_factory=lambda: Program.query,
                                widget=Select())
    photo_upload = FileField('Photo Upload')


class EducationForm(ModelForm):
    class Meta:
        model = Education


class IntlConferenceSupportForm(ModelForm):
    class Meta:
        model = IntlConferenceSupport
    qualifications = [(c, c) for c in
                      ('บุคลากรสถาบันฯและไม่อยู่ระหว่างลาศึกษา/ไปปฏิบัติงานเพื่อเพิ่มพูนความรู้',
                       'ปฎิบัติงานในสถาบันมาแล้วไม่น้อยกว่า 1 ปีและไม่อยู่ในระหว่างการลาศึกษาเต็มเวลา',
                       'ยังไม่เคยขอรับความสนับสนุน / เคยขอรับการสนับสนุนและตีพิมพ์เผยแพร่งานตามประกาศแล้ว',
                       'เป็นผู้เขียนชื่อแรกและหรือผู้รับผิดชอบหลัก')]
    qualification_select = MultiCheckboxField('คุณสมบัติของผู้ขอรับการสนับสนุนตามประกาศฯ',
                                              choices=qualifications)


class DevelopmentTypeForm(ModelForm):
    class Meta:
        model = DevelopmentType


class DevelopmentCategoryForm(ModelForm):
    class Meta:
        model = DevelopmentCategory


class DevelopmentExpenseItemForm(ModelForm):
    class Meta:
        model = DevelopmentExpenseItem
        csrf = False


class DevelopmentRecordForm(ModelForm):
    class Meta:
        model = DevelopmentRecord

    development_type = QuerySelectField('ประเภทการพัฒนา', query_factory=lambda: DevelopmentType.query.all(),
                                        get_label='name', allow_blank=False, blank_text='เลือกประเภท')
    development_category = QuerySelectField('หมวดการพัฒนา', query_factory=lambda: DevelopmentCategory.query.all(),
                                        get_label='name', allow_blank=False, blank_text='เลือกหมวด')
    file_upload = FileField('Upload หนังสืออนุมัติ')
    items = FieldList(FormField(DevelopmentExpenseItemForm, default=DevelopmentExpenseItem), min_entries=5)

erm/app/researcher/__init__.py
from flask import Blueprint

researcher_bp = Blueprint('researcher', __name__)

from . import views

erm/app/researcher/views.py
import datetime
import os
import requests
import arrow
from flask import render_template, flash, request, redirect, url_for, session
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename
from app.main.models import User
from app.researcher.models import Profile, Education, IntlConferenceSupport, DevelopmentRecord
from app.researcher.forms import ProfileForm, EducationForm, IntlConferenceSupportForm, DevelopmentRecordForm
from app import db
from . import researcher_bp as researcher
from app.project.models import (ProjectPublication,
                                ProjectPublicationAuthor,
                                ProjectPublicationJournal, ProjectPublishedReward, ProjectLanguageEditingSupport)
from app.project.forms import (ProjectPublicationForm,
                               ProjectJournalForm,
                               ProjectPublicationAuthorForm, ProjectPublishedRewardForm, ProjectLanguageEditSupportForm)
from pydrive.auth import ServiceAccountCredentials, GoogleAuth
from pydrive.drive import GoogleDrive

gauth = GoogleAuth()
keyfile_dict = requests.get(os.environ.get('GOOGLE_APPLICATION_CREDENTIALS')).json()
scopes = ['https://www.googleapis.com/auth/drive']
gauth.credentials = ServiceAccountCredentials.from_json_keyfile_dict(keyfile_dict, scopes)
drive = GoogleDrive(gauth)


@researcher.route('/profile/<int:user_id>')
@login_required
def show_profile(user_id):
    user = User.query.get(user_id)
    if not user.profile:
        profile = Profile(user_id=user.id)
        db.session.add(profile)
        db.session.commit()
    return render_template('researcher/profile.html', user=user)


@researcher.route('/profile/edit/<int:user_id>', methods=['GET', 'POST'])
@login_required
def edit_profile(user_id):
    user = User.query.get(user_id)
    form = ProfileForm(obj=user.profile, programs=user.profile.program)
    if request.method == 'POST':
        if form.validate_on_submit():
            form.populate_obj(user.profile)
            photo_file = form.photo_upload.data
            if photo_file:
                filename = secure_filename(photo_file.filename)
                photo_file.save(filename)
                file_drive = drive.CreateFile({'title': filename})
                file_drive.SetContentFile(filename)
                file_drive.Upload()
                permission = file_drive.InsertPermission({'type': 'anyone',
                                                          'value': 'anyone',
                                                          'role': 'reader'})
                user.profile.photo_url = file_drive['id']
                print(user.profile.photo_url)
            user.profile.program = form.programs.data
            db.session.add(user.profile)
            db.session.commit()
            flash('Data has been saved.', 'success')
            return redirect(url_for('researcher.show_profile', user_id=user.id))
        else:
            flash('Errors occurred.', 'danger')
            return redirect(url_for('researcher.show_profile', user_id=user.id))
    return render_template('researcher/profile_edit.html', form=form)



@researcher.route('/profile/<int:profile_id>/education/new', methods=['GET', 'POST'])
@login_required
def add_education(profile_id):
    profile = Profile.query.get(profile_id)
    form = EducationForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            new_edu = Education()
            new_edu.profile = profile
            form.populate_obj(new_edu)
            db.session.add(new_edu)
            db.session.commit()
            flash('New record has been added.', 'success')
        else:
            flash('Error occurred.', 'danger')
        return redirect(url_for('researcher.show_profile', user_id=profile.user_id))

    return render_template('researcher/education_add.html', form=form)


@researcher.route('/profile/education/<int:edid>/edit', methods=['GET', 'POST'])
@login_required
def edit_education(edid):
    edu = Education.query.get(edid)
    form = EducationForm(obj=edu, degree=edu.degree)
    if request.method == 'POST':
        if form.validate_on_submit():
            form.populate_obj(edu)
            db.session.add(edu)
            db.session.commit()
            flash('Record has been edited.', 'success')
        else:
            flash('Error occurred.', 'danger')
        return redirect(url_for('researcher.show_profile', user_id=edu.profile.user_id))

    return render_template('researcher/education_add.html', form=form)


@researcher.route('/profile/education/<int:edid>/remove', methods=['GET', 'POST'])
@login_required
def remove_education(edid):
    edu = Education.query.get(edid)
    user_id = edu.profile.user_id
    try:
        db.session.delete(edu)
        db.session.commit()
    except:
        flash('Error occurred.')
    else:
        flash('Record has been removed', 'success')
    return redirect(url_for('researcher.show_profile', user_id=user_id))


@researcher.route('/journals/add', methods=['GET', 'POST'])
@login_required
def add_journal():
    dest = request.args.get('next')
    pub_id = request.args.get('pub_id')
    form = ProjectJournalForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            new_journal = ProjectPublicationJournal()
            form.populate_obj(new_journal)
            db.session.add(new_journal)
            db.session.commit()
            flash('New journal has been added.', 'success')
            return redirect(url_for(dest, pub_id=pub_id))
        else:
            flash(form.errors, 'danger')
    return render_template('researcher/journal_add.html', form=form)


@researcher.route('/pubs/add', methods=['GET', 'POST'])
@login_required
def add_pub():
    form = ProjectPublicationForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            new_pub = ProjectPublication()
            form.populate_obj(new_pub)
            new_pub.journal = form.journals.data
            author = ProjectPublicationAuthor()
            author.user = current_user
            new_pub.authors.append(author)
            new_pub.creator = current_user
            db.session.add(author)
            db.session.add(new_pub)
            db.session.commit()
            flash('New publication added.', 'success')
            return redirect(url_for('researcher.show_profile',
                                    user_id=current_user.id))
        else:
            flash('Error occurred.', 'danger')
    return render_template('researcher/pub_add.html', form=form)


@researcher.route('/pubs/<int:pub_id>')
@login_required
def show_pub(pub_id):
    pub = ProjectPublication.query.get(pub_id)
    return render_template('researcher/pub_detail.html', pub=pub)


@researcher.route('/pubs/<int:pub_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_pub(pub_id):
    pub = ProjectPublication.query.get(pub_id)
    form = ProjectPublicationForm(obj=pub)
    if request.method == 'POST':
        if form.validate_on_submit():
            form.populate_obj(pub)
            db.session.add(pub)
            db.session.commit()
            flash('Data have been saved.', 'success')
            return redirect(url_for('researcher.show_profile',
                                    user_id=current_user.id))
        else:
            flash(form.errors, 'danger')
    return render_template('researcher/pub_edit.html', form=form, pub=pub)


@researcher.route('/pubs/<int:pub_id>/authors/edit', methods=['GET', 'POST'])
@login_required
def edit_pub_authors(pub_id):
    dest = request.args.get('next')
    pub = ProjectPublication.query.get(pub_id)
    return render_template('researcher/pub_author_edit.html', pub=pub, dest=dest)


@researcher.route('/pubs/<int:pub_id>/authors/add', methods=['GET', 'POST'])
@login_required
def add_pub_author(pub_id):
    pub = ProjectPublication.query.get(pub_id)
    form = ProjectPublicationAuthorForm()
    dest = request.args.get('next')
    if request.method == 'POST':
        if form.validate_on_submit():
            new_author = ProjectPublicationAuthor()
            form.populate_obj(new_author)
            new_author.pub = pub
            new_author.user = form.users.data
            db.session.add(new_author)
            db.session.commit()
            flash('New author has been added.', 'success')
            return redirect(url_for('researcher.edit_pub_authors',
                                    pub_id=pub_id, next=dest))
        else:
            flash(form.errors, 'danger')
    return render_template('researcher/pub_author_add.html',
                           pub=pub, form=form, dest=dest)


@researcher.route('/pubs/<int:pub_id>/authors/<int:author_id>/remove', methods=['GET', 'POST'])
@login_required
def remove_pub_author(pub_id, author_id):
    author = ProjectPublicationAuthor.query.get(author_id)
    if author:
        db.session.delete(author)
        db.session.commit()
        flash('Author has been deleted from publication', 'success')
    else:
        flash('The author with that ID was not found.', 'danger',)
    return redirect(url_for('researcher.edit_pub_authors', pub_id=pub_id))


@researcher.route('/pubs/<int:pub_id>/remove', methods=['GET', 'POST'])
@login_required
def remove_pub(pub_id):
    pub = ProjectPublication.query.get(pub_id)
    confirm = request.args.get('confirm', 'no')
    if confirm == 'yes':
        if pub:
            db.session.delete(pub)
            db.session.commit()
            flash('The publication has been removed from database.', 'success')
            return redirect(url_for('researcher.show_profile', user_id=current_user.id))
        else:
            flash('The publication does not exist.', 'danger',)
    return render_template('researcher/pub_remove.html', pub=pub)


@researcher.route('/intl-support/add', methods=['GET', 'POST'])
@login_required
def add_intl_conference_support():
    form = IntlConferenceSupportForm()

erm/app/templates/researcher/profile.html
{% extends "base.html" %}

{% block title %}Profile Page{% endblock %}
{% block page_content %}
{% include "nav.html" %}
<section class="hero is-info">
</section>
<section class="section">
    <div class="columns">
        <div class="column is-three-fifths is-offset-one-fifth">
            {% include "messages.html" %}
        </div>
    </div>
    <div class="columns">
        <div class="column is-three-fifths is-offset-one-fifth">
            <div class="box has-text-centered">
                <h2 class="title">Profile</h2>
                {% if user.profile.photo_url %}
                <img width="128" height="128" src="https://drive.google.com/uc?id={{ user.profile.photo_url }}">
                {% else %}
                <img width="128" height="128" src="{{ url_for('static', filename='images/account.png') }}">
                {% endif %}
                <br/>
                {% if current_user.is_authenticated and current_user.id == user.id %}
                <a href="{{ url_for('researcher.edit_profile', user_id=user.id) }}"
                    class="button is-rounded is-success">
                    <span class="icon">
                        <i class="fas fa-pencil-alt"></i>
                    </span>
                    <span>แก้ไขประวัติ</span>
                </a>
                {% endif %}
                <hr>
                <table class="table is-fullwidth">
                    <tr>
                        <td class="title is-size-5">Thai Name</td>
                        <td>{{ user.profile.title_th or '' }} {{ user.profile.fullname_th or '-' }}</td>
                    </tr>
                    <tr>
                        <td class="title is-size-5">English Name</td>
                        <td>{{ user.profile.title_en or '' }} {{ user.profile.fullname_en or '-' }}</td>
                    </tr>
                    <tr>
                        <td class="title is-size-5">E-mail</td>
                        <td>{{ user.email }}</td>
                    </tr>
                    {% if current_user.is_authenticated and current_user.id == user.id %}
                    <tr>
                        <td class="title is-size-5">Password</td>
                        <td>
                            <a href="{{ url_for('auth.edit_password') }}"
                               class="has-text-danger">Change Password</a>
                        </td>
                    </tr>
                    {% endif %}
                    <tr>
                        <td class="title is-size-5">Program</td>
                        <td>{{ user.profile.program or '-' }}</td>
                    </tr>
                    <tr>
                        <td class="title is-size-5">ตำแหน่งปัจจุบัน</td>
                        <td>{{ user.profile.position or '-' }}</td>
                    </tr>
                    <tr>
                        <td class="title is-size-5">สาขาวิชาการที่มีความชำนาญพิเศษ</td>
                        <td>{{ user.profile.field_expertise or '-' }}</td>
                    </tr>
                    <tr>
                        <td class="title is-size-5">ประสบการณ์ที่เกี่ยวข้องกับการบริหารงานวิจัย</td>
                        <td class="content">{{ user.profile.experience|safe or '-' }}</td>
                    </tr>
                    <tr>
                        <td class="title is-size-5">Education</td>
                        <td>
                        <table class="table is-fullwidth is-striped is-narrow">
                            {% for ed in user.profile.educations|sort(attribute='year', reverse=True) %}
                            <tr>
                                <td class="title is-size-6">Level</td>
                                <td class="title is-size-6">{{ ed.degree|title }}</td>
                                <td>
                                    {% if current_user.is_authenticated and current_user.id==user.id %}
                                    <a href="{{ url_for('researcher.edit_education', edid=ed.id) }}"
                                        class="button is-small is-primary is-outlined">
                                        <span class="icon">
                                            <i class="fas fa-pencil-alt"></i>
                                        </span>
                                        <span>แก้ไข</span>
                                    </a>
                                    <a href="{{ url_for('researcher.remove_education', edid=ed.id) }}"
                                       class="button is-small is-outlined is-danger">
                                        <span class="icon">
                                            <i class="fas fa-trash-alt"></i>
                                        </span>
                                        <span>ลบทิ้ง</span>
                                    </a>
                                    {% endif %}
                                </td>
                            </tr>
                            <tr>
                                <td>Title</td>
                                <td>{{ ed.degree_title|title }}</td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>Year</td>
                                <td>{{ ed.year }}</td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>Program</td>
                                <td>{{ ed.program or '-' }}</td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>Field</td>
                                <td>{{ ed.field or '-' }}</td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>University</td>
                                <td>{{ ed.university or '-' }}</td>
                                <td></td>
                            </tr>
                            <tr>
                                <td colspan="3"></td>
                            </tr>
                            {% endfor %}
                            {% if current_user.is_authenticated and current_user.id == user.id %}
                            <tr>
                                <td></td>
                                <td>
                                    <a href="{{ url_for('researcher.add_education', profile_id=user.profile.id) }}"
                                        class="button is-rounded is-success is-small">
                                        <span class="icon">
                                            <i class="fas fa-plus"></i>
                                        </span>
                                        <span>เพิ่มประวัติการศึกษา</span>
                                    </a>
                                </td>
                                <td></td>
                            </tr>
                            {% endif %}
                        </table>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</section>
<section class="section">
    <div class="columns">
        <div class="column is-three-fifths is-offset-one-fifth">
            <div class="box has-text-centered">
                <h2 class="title">Publication</h2>
                {% if current_user.is_authenticated and current_user.id == user.id %}
                <a href="{{ url_for('researcher.add_pub') }}"
                    class="button is-success is-rounded">
                <span class="icon">
                    <i class="fas fa-plus"></i>
                </span>
                    <span>เพิ่มผลงานวิจัยใหม่</span>
                </a>
                {% endif %}
                <table class="table is-striped is-fullwidth">
                    <thead>
                    <th>No.</th>
                    <th>Title</th>
                    <th>Journal</th>
                    <th>Published</th>
                    </thead>
                    <tbody>
                    {% for pub in user.publications %}
                    <tr>
                        <td>{{ loop.index }}</td>
                        <td><a href="{{ url_for('researcher.show_pub', pub_id=pub.id) }}">{{ pub.title }}</a></td>
                        <td>{{ pub.journal }}</td>
                        <td>{{ pub.pub_date|localdate }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<section class="section">
    <div class="columns">
        <div class="column is-three-fifths is-offset-one-fifth">
            <div class="box has-text-centered">
                <h2 class="title">International Conference Supports</h2>
                {% if current_user.is_authenticated and current_user.id == user.id %}
                <a href="{{ url_for('researcher.add_intl_conference_support') }}"
                    class="button is-rounded is-success">
                <span class="icon">
                    <i class="fas fa-plus"></i>
                </span>
                    <span>ยื่นขออนุมัติเงินสนับสนุน</span>
                </a>
                {% endif %}
                <table class="table is-striped is-fullwidth">
                    <thead>
                    <th>No.</th>
                    <th>ยื่นวันที่</th>
                    <th>จำนวนเงิน</th>
                    <th>สถานที่ประชุม</th>
                    <th>สถานะ</th>
                    <th>อนุมัติวันที่</th>
                    </thead>
                    <tbody>
                    {% for support in user.intl_conference_supports %}
                    <tr>
                        <td>{{ loop.index }}</td>
                        <td>{{ support.submitted_at|localdatetime }}</td>
                        <td>{{ support.amount }}</td>
                        <td>{{ support.venue }}</td>
                        <td>
                            {% if support.approved_at %}
                            <span class="icon">
                                <i class="far fa-check-circle has-text-success"></i>
                            </span>
                            <span>อนุมัติ</span>
                            {% endif %}
                        </td>
                        <td>
                            {% if support.approved_at %}
                            {{ support.approved_at|localdatetime }}
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<section class="section">
    <div class="columns">
        <div class="column is-three-fifths is-offset-one-fifth">
            <div class="box has-text-centered">
                <h2 class="title">Development Supports</h2>
                {% if current_user.is_authenticated and current_user.id == user.id %}
                <a href="{{ url_for('researcher.add_development_support') }}"
                   class="button is-rounded is-success">
                <span class="icon">
                    <i class="fas fa-plus"></i>
                </span>
                    <span>ยื่นขออนุมัติเงินสนับสนุนการพัฒนาตนเอง</span>
                </a>
                {% endif %}
                <table class="table is-striped is-fullwidth">
                    <thead>
                    <th>No.</th>
                    <th>หัวข้อ</th>
                    <th>ประเภท</th>
                    <th>หมวด</th>
                    <th>สถานที่</th>
                    <th>ยื่นวันที่</th>
                    <th>สถานะ</th>
                    <th>อนุมัติวันที่</th>
                    </thead>
                    <tbody>
                    {% for support in user.development_records %}
                    <tr>
                        <td>{{ loop.index }}</td>
                        <td>{{ support.topic }}</td>
                        <td>{{ support.development_type.name }}</td>
                        <td>{{ support.development_category.name }}</td>
                        <td>{{ support.venue }}</td>
                        <td>{{ support.submitted_at|localdatetime }}</td>
                        <td>
                            {% if support.approved_at %}
                            <span class="icon">
                                <i class="far fa-check-circle has-text-success"></i>
                            </span>
                            <span>อนุมัติ</span>
                            {% else %}
                            pending
                            {% endif %}
                        </td>
                        <td>
                            {% if support.approved_at %}
                            {{ support.approved_at|localdatetime }}
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock %}

erm/app/templates/researcher/pub_author_add.html
{% extends "base.html" %}

{% block title %}Add Author{% endblock %}
{% block page_content %}
{% include "nav.html" %}
<section class="section">
    <div class="columns">
        <div class="column is-half is-offset-one-quarter">
            <h1 class="title has-text-centered">Add New Author</h1>
            {% include 'message.html' %}
            <form method="post" class="box" action="{{ url_for('researcher.add_pub_author', pub_id=pub.id, next=dest) }}">
                {{ form.csrf_token }}
                <input name="source" value="1" type="hidden">
                <div class="field">
                    <label class="label">Researchers</label>
                    <div class="control">
                        <div class="select">
                            {{ form.users() }}
                       </div>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <button type="submit" class="button is-primary">Add</button>
                    </div>
                </div>
            </form>
             <form method="post" class="box">
                {{ form.csrf_token }}
                <input name="source" value="2" type="hidden">
                <div class="field">
                    <label class="label">First Name</label>
                    <div class="control">
                        {{ form.firstname(class="input") }}
                    </div>
                </div>
                <div class="field">
                    <label class="label">Last Name</label>
                    <div class="control">
                        {{ form.lastname(class="input") }}
                    </div>
                </div>
                <div class="field">
                    <label class="label">Affiliation</label>
                    <div class="control">
                        {{ form.affil(class="input") }}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <button type="submit" class="button is-primary">Add</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

erm/app/templates/researcher/pub_author_edit.html
{% extends "base.html" %}

{% block title %}Edit Publication Authors{% endblock %}
{% block page_content %}
{% include "nav.html" %}
<section class="section">
    <div class="columns">
        <div class="column is-half is-offset-one-quarter">
            <h1 class="title has-text-centered">Authors</h1>
            {% include 'message.html' %}
            <div class="box">
                <table class="table is-fullwidth">
                    <thead>
                        <th>No.</th>
                        <th>Name</th>
                        <th>Affiliation</th>
                        <th></th>
                    </thead>
                    <tbody>
                        {% for a in pub.authors %}
                        <tr>
                            <td>{{ loop.index }}</td>
                            {% if a.user_id %}
                                <td>{{ a.user.profile }}</td>
                                <td>{{ a.user.profile.affiliation }}</td>
                            {% else %}
                                <td>{{ a.fullname }}</td>
                                <td>{{ a.affil }}</td>
                            {% endif %}
                            <td>
                                {% if project_id %}
                                <a href="{{ url_for('project.remove_pub_author', pub_id=pub.id, author_id=a.id, project_id=project_id) }}">
                                {% else %}
                                <a href="{{ url_for('researcher.remove_pub_author', pub_id=pub.id, author_id=a.id) }}">
                                {% endif %}
                                    <span class="icon">
                                        <i class="fas fa-trash-alt
                                            has-text-danger"></i>
                                    </span>
                                </a>
                            </td>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="buttons is-centered">
                {% if project_id %}
                <a href="{{ url_for('project.add_pub_author', pub_id=pub.id, project_id=project_id) }}"
                {% else %}
                <a href="{{ url_for('researcher.add_pub_author', pub_id=pub.id, next=dest) }}"
                {% endif %}
                   class="button is-primary">
                    <span class="icon">
                        <i class="fas fa-user-plus"></i>
                    </span>
                    <span>Add</span>
                </a>
                {% if project_id %}
                <a href="{{ url_for('project.edit_pub', pub_id=pub.id, project_id=project_id)}}" class="button is-success">
                    <span>Done</span>
                </a>
                {% else %}
                <a href="{{ url_for(dest, pub_id=pub.id) }}" class="button is-success">
                    <span>Done</span>
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}