web/project_root/research/urls.py
from django.urls import path
from . import views


app_name = 'research'

urlpatterns = [
    path('', views.project_list, name='project_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:project>/',
         views.project_detail, name='project_detail'),
    path('irb-record/<int:irbid>/',
         views.irb_detail, name='irb_detail'),
]

web/project_root/web/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls
from wagtail.core import urls as wagtail_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('research/', include('research.urls', namespace='research')),
    path('staff/', include('users.urls', namespace='staff')),
    re_path(r'^cms/', include(wagtailadmin_urls)),
    re_path(r'^documents/', include(wagtaildocs_urls)),
    re_path(r'^pages/', include(wagtail_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/project_root/research/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from users.models import CustomUser


class OngoingManager(models.Manager):
    def get_queryset(self):
        return super(OngoingManager, self).get_queryset().filter(status='began')

class ProjectCategory(models.Model):
    name = models.CharField(max_length=64)
    slug = models.SlugField(max_length=250, unique=True)


class ProjectSubCategory(models.Model):
    main_category = models.ForeignKey(ProjectCategory,
                                      on_delete=models.CASCADE,
                                      related_name='subs')
    name = models.CharField(max_length=64)
    slug = models.SlugField(max_length=250, unique=True)

# Create your models here.
class Project(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('ended', 'Ended'),
        ('began', 'Began'),
        ('holding', 'Holding'),
        ('terminated', 'Terminated'),
    )

    objects = models.Manager()
    ongoing = OngoingManager()

    en_title = models.CharField(max_length=250)
    th_title = models.CharField(max_length=250)
    intro = models.TextField(null=True)
    objective = models.TextField(null=True)
    method = models.TextField(null=True)
    budget = models.FloatField(null=True)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    creator = models.ForeignKey(CustomUser,
                                on_delete=models.CASCADE,
                                related_name='created_projects'
                                )
    th_abstract = models.TextField()
    # probably should leave out the full text instead the client requests.
    startdate = models.DateField(null=True)
    enddate = models.DateField(null=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    category = models.ForeignKey(ProjectSubCategory,
                                 on_delete=models.DO_NOTHING,
                                 related_name='projects',
                                 null=True,
                                 blank=True
                                 )

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        # display Thai title or English
        return self.th_title or self.en_title

    def get_absolute_url(self):
        return reverse('research:project_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug
                             ])


class IRBRecord(models.Model):
    STATUS_CHOICES = (
        ('approved', 'Approved'),
        ('disapproved', 'Not approved'),
        ('pending', 'Pending'),
        ('submitted', 'Submitted'),
        ('exempted', 'Exempted'),
    )
    irbcode = models.CharField(max_length=120)
    status = models.CharField(max_length=32,
                              choices=STATUS_CHOICES,
                              default='exempted')

    submitdate = models.DateField(default=timezone.now)
    creator = models.ForeignKey(CustomUser,
                                on_delete=models.CASCADE,
                                related_name='irb_records'
                                )
    project = models.ForeignKey(Project,
                                on_delete=models.CASCADE,
                                related_name='irb_records')
    updated = models.DateTimeField(auto_now_add=True)


class Publication(models.Model):
    pubdate = models.DateField('publication date')
    creator = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="pubs")
    added_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    journal = models.CharField(max_length=250)
    title = models.CharField(max_length=250)
    abstract = models.TextField(blank=True)
    url = models.URLField(blank=True)

web/project_root/research/forms.py
from django import forms
from .models import Project


class ProjectSearchForm(forms.Form):
    query = forms.CharField()

web/project_root/research/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.postgres.search import SearchVector
from django.shortcuts import render, get_object_or_404
from .models import Project, IRBRecord
from .forms import ProjectSearchForm


def project_list(request):
    form = ProjectSearchForm()
    query = None
    if 'query' in request.GET:
        form = ProjectSearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            projects = Project.objects.annotate(
                search=SearchVector('en_title', 'th_title', 'th_abstract')).filter(search=query)
    else:
        projects = Project.ongoing.all()
    return render(request,
                  'research/project/list.html',
                  {'projects': projects, 'form': form, 'query': query})


def project_detail(request, year, month, day, project):
    project = get_object_or_404(Project, slug=project,
                                publish__year=year,
                                publish__month=month,
                                publish__day=day)
    thai_status = {'began': 'เริ่มดำเนินการแล้ว',
                   'drafted': 'ร่างโครงการ'}
    try:
        irb = project.irb_records.all()[0]
    except IndexError:
        irb = None
    return render(request,
                  'research/project/detail.html',
                  {'project': project, 'thai_status': thai_status, 'irb': irb})


def irb_detail(request, irbid):
    irb = get_object_or_404(IRBRecord, pk=irbid)
    return render(request, 'research/project/irb_detail.html', {'irb': irb})

web/project_root/research/templates/research/project/detail.html
{% extends "research/base.html" %}

{% block title %}Research Project: Detail{% endblock %}
{% block page_header %}Research Project Detail{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <p class="title">ชื่อโครงการ{{ project.th_title }}</p>
        <p class="subtitle">{{ project.en_title }}</p>
        <article class="notification">
            <h1 class="title">บทคัดย่อ</h1>
            <p class="has-text-justified">{{ project.th_abstract }}</p>
        </article>
        <table class="table is-fullwidth">
            <tr>
                <td>ลงทะเบียนเมื่อ</td><td>{{ project.publish }}</td>
            </tr>
            <tr>
                <td>ลงทะเบียนโดย</td><td>
                    <a href="{{ project.creator.get_absolute_url }}">
                    {{ project.creator }}
                    </a>
                </td>
            </tr>
            <tr>
                <td>สถานภาพโครงการ</td><td>{{ project.status }}</td>
            </tr>
            <tr>
                <td>วันเริ่มโครงการ</td><td>{{ project.startdate }}</td>
            </tr>
            <tr>
                <td>วันสิ้นสุดโครงการ</td><td>{{ project.enddate }}</td>
            </tr>
            <tr>
                <td>สถานภาพโครงการ</td><td>{{ project.status }}</td>
            </tr>
            <tr>
                <td>ทุนสนับสนุน</td><td>{{ project.budget }} บาท</td>
            </tr>
            <tr>
                <td>สถานะการขออนุมัติทางจริยธรรมวิจัย</td>
                {% if irb %}
                <td><a href="{% url 'research:irb_detail' irb.pk %}">{{ irb.status }}</a>
                {% else %}
                <td>ยังไม่มีรายการ</td>
                {% endif %}
                </td>
            </tr>
        </table>
    </div>
</section>
{% endblock %}

web/project_root/research/templates/research/project/irb_detail.html
{% extends "research/base.html" %}

{% block title %}IRB Record Detail{% endblock %}

{% block page_header %}IRB Record Detail{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="card-header-title">
                    หมายเลข {{ irb.irbcode }}
                </div>
            </div>
            <div class="card-content">
                <h1 class="title is-size-4">
                    {{ irb.project.en_title }}
                </h1>
                <h1 class="subtitle is-size-4">
                    {{ irb.project.th_title }}
                </h1>
                <p>
                    ส่งโดย {{ irb.creator }}
                </p>
                <p>
                    ส่งเมื่อ {{ irb.submitdate }}
                </p>
                <p>
                    สถานภาพ {{ irb.status }}
                </p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

web/project_root/research/templates/research/project/list.html
{% extends "research/base.html" %}

{% block title %}Ongoing Projects{% endblock %}

{% block page_subheader %}All ongoing projects{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column">
                {% if query %}
                <h2 class="title is-size-4">
                    Projects containing : {{ query }}
                </h2>
                {% with projects.count as total_results %}
                <p class="tag is-large"><strong>Found</strong>&nbsp; {{ total_results }}&nbsp; project{{ total_results|pluralize }}</p>
                {% endwith %}
                {% endif %}
                {% for project in projects %}
                <h2 class="title">
                    <a href="{{ project.get_absolute_url }}">
                        {{ project.th_title }}
                    </a>
                </h2>
                <h2 class="subtitle">
                    {{ project.en_title}}
                </h2>
                <article class="notification">
                    <h3 class="title is-size-5">Abstract</h3>
                    <p class="has-text-justified">
                        {{ project.th_abstract }}
                    </p>
                </article>
                <p class="has-text-right">
                    Added at {{ project.publish }} by {{ project.creator }}
                    <span class="icon is-large">
                        <i class="fas fa-user-circle fa-3x"></i>
                    </span>
                </p>
                {% endfor %}
            </div>
            <div class="column is-one-fifth">
                <h1 class="title">Search for projects</h1>
                <form action="." method="get">
                    {{ form.as_p }}
                    {% csrf_token %}
                </form>
                <a href="{% url 'research:project_list' %}">
                    All projects
                </a>
            </div>
        </div>
    </div>
</section>
{% endblock %}